# Generated by Django 5.2.8 on 2025-11-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusermodel',
            name='c_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminusermodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
