# Generated by Django 5.2.8 on 2025-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0002_alter_adminusermodel_c_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
