# Generated by Django 5.2.8 on 2025-11-25 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0003_alter_adminusermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notesApp.adminusermodel'),
        ),
    ]
